# 配置应用名称
spring:
  application:
    name: eureka1
# 注册管理中心端口
server:
  port: 8762

# 配置eureka客户端
eureka:
  instance:
    hostname: eureka-cluster1
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-cluster2:8763/eureka/,http://eureka-cluster3:8764/eureka/

spring.cloud.config.discovery.enable: true
